### ISSUE TITLE
kusama version doesn't collect information past jan 3rd up to the current date. 

### ISSUE THREAD

**Issue by jhonalino** [w3f/staking-rewards-collector#27]
hello I've ran this with current date on the config as seen on the screen shot. but the kusama version doesn't return data past that jan 3rd. am I missing something ? 

![Screen Shot 2021-06-08 at 10 56 50 AM](https://user-images.githubusercontent.com/13143458/121234502-a072a300-c848-11eb-91c3-f0863fff92da.png)

I'm also working on a frontend UI here and it shows the same limit. 
https://www.stakingrewards.network/rewards?addresses=%5B%7B%22name%22%3A%22%22%2C%22startBalance%22%3A%22%22%2C%22address%22%3A%22G1rrUNQSk7CjjEmLSGcpNu72tVtyzbWdUvgmSer9eBitXWf%22%2C%22error%22%3Anull%2C%22network%22%3A%22kusama%22%7D%2C%7B%22name%22%3A%22%22%2C%22startBalance%22%3A%22%22%2C%22address%22%3A%2215fTw39Ju2jJiHeGe1fJ5DtgugUauy9tr2HZuiRNFwqnGQ1Q%22%2C%22error%22%3Anull%2C%22network%22%3A%22polkadot%22%7D%5D&endDate=3&endMonth=6&endYear=2021&selectedCurrency=USD&startDate=1&startMonth=12&startYear=2020

thank you very much !

**Comment by jhonalino** [comment]
dot is working just fine.

**Comment by jhonalino** [comment]
the reason I brought this up is because I notice this tool is returning data up to current date and it has rewards data

https://www.cryptolab.network/tools/dotSR for G1rrUNQSk7CjjEmLSGcpNu72tVtyzbWdUvgmSer9eBitXWf

**Comment by jonasW3F** [comment]
That is indeed quite odd. The staking rewards collectors uses subscan's API to get the staking rewards. Indeed, when going to their page for the address we talk about: https://kusama.subscan.io/account/G1rrUNQSk7CjjEmLSGcpNu72tVtyzbWdUvgmSer9eBitXWf?tab=reward the last staking reward is from the 4th of january.

I checked with polkastats and it indeed seems that there are more staking rewards for that address. I'll contact subscan.

**Comment by jonasW3F** [comment]
Everything is working fine, the account changed the reward destination and subscan matches the reward to the reward destination. Polkascan matches all rewards generated by the stash account to it. That's just a different logic how to display the rewards and I think that the way subscan is doing it, is more intuitive and expected and therefore shouldn't cause any UX problems.
