### ISSUE TITLE
legacy subscan api being deprecated

### ISSUE THREAD

**Issue by jhonalino** [w3f/staking-rewards-collector#28]
from subscan announcement it looks like the legacy api is being deprecated
https://docs.api.subscan.io/#introduction

and from this tweet
https://twitter.com/subscan_io/status/1399603110138433537

the new API will take the form of https://[NETWORK].api.subscan.io/

from what it was: 
https://kusama.subscan.io/api

and it looks like they gonna require Auth key with the new one. which is gonna be a problem if this is to be hosted on ipfs
where everything should run client side it will quickly reach qouta for sufficient amount of traffic

**Comment by jonasW3F** [comment]
Thanks for the information. The script is currently still working with the old API format. I'll upgrade it to the new format. The Auth key is indeed a problem for hosting it on IPFS. Maybe there are some ways around it like buying an Auth key from the treasury to prevent quota limits?

**Comment by jonasW3F** [comment]
fixed in https://github.com/w3f/staking-rewards-collector/pull/29
