### ISSUE TITLE
Subscan API rate limit issue

### ISSUE THREAD

**Issue by bjweaver** [w3f/staking-rewards-collector#31]
Subscan implemented an API rate limit, causing rewards calculation to fail..  I added a basic 100ms sleep to the API calls.

https://github.com/w3f/staking-rewards-collector/pull/30

**Comment by jonasW3F** [comment]
I encountered the issue also. Will take a look.

**Comment by bjweaver** [comment]
yes, seeing the same error, seems unrelated to the rate limit issue.  Looks like the loopIndex it over running the amount of records returned on the last page.  Something weird with the subscan data probably.  If you change line 41 to this, it works, but this might not be the right fix.

loopIndex = min(stakingObject.data.count - page*100 - 1,100);

**Comment by jonasW3F** [comment]
yes, I also saw that reducing the loopindex would help, but a quick check showed that not all rewards would be parsed then. I first need to understand if the API changed.

**Comment by jonasW3F** [comment]
Subscan confirmed that it is an issue on their side. They have too many requests on their Kusama API and their service times out. They are trying to solve this. Once it is resolved, I will check your PR #30 and merge it. 

Thank you!
