### ISSUE TITLE
Fix user input validation error message

### ISSUE THREAD

**Issue by jrmykolyn** [w3f/staking-rewards-collector#38]
I was digging through some of the utility functions and I notice that one of the error messages thrown by `verifyUserInput()` is incorrect. The incorrect error message can be seen here: https://github.com/w3f/staking-rewards-collector/blob/master/src/utils.js#L189

I've introduced a pull request to fix this here: https://github.com/w3f/staking-rewards-collector/pull/37

Thanks!

**Comment by jonasW3F** [comment]
thanks
