### ISSUE TITLE
ENHANCEMENT: Allow default or "N/A" for periods when no price available

### ISSUE THREAD

**Issue by laboon** [w3f/staking-rewards-collector#8]
For 19 Aug or earlier, there is no price data from CoinGecko as DOT was not trading.

When you ask for a time period where there is no price data, can you allow either a default (preferably specified) or simply show "0" or "n/a", instead of exiting?

This would only apply to accounts where the owner:
1: bought pre-summer 2020 
2: claimed before 19 Aug 
3: started validating after claiming but before 19 Aug

Thus, I would say this is low-priority (and workaround is relatively simple, split into pre-19 Aug and post-19 Aug where pre version has 'n' for `priceData`, then manually calculate with default price on a spreadsheet)

**Comment by jonasW3F** [comment]
Making an API request to CoinGecko for a period including at least one day without prices will return an error. The script still continues but uses prices of 0 for all the dates. 

What could work is to search for the day with the first available price in the object and then only make price calls from there. The easiest way then would be to start form that iteration index only.

**Comment by jonasW3F** [comment]
I did some adjustments and pushed a branch "v1.2" which should solve this issue.

**Comment by jonasW3F** [comment]
This should be fixed in v1.2. Users are now free to request any time period with price data enabled.
